// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function print(_node) {
  while(true) {
    var node = _node;
    if (node) {
      print(node[1]);
      Pervasives.print_int(node[0]);
      Pervasives.print_string(", ");
      _node = node[2];
      continue ;
      
    } else {
      return Pervasives.print_string("");
    }
  };
}

function find(_node, value) {
  while(true) {
    var node = _node;
    if (node) {
      var v = node[0];
      var match = +(v === value || value < v);
      if (match !== 0) {
        _node = node[1];
        continue ;
        
      } else {
        _node = node[2];
        continue ;
        
      }
    } else {
      return /* false */0;
    }
  };
}

function insert(node, value) {
  if (node) {
    var r = node[2];
    var l = node[1];
    var v = node[0];
    var match = +(value < v);
    if (match !== 0) {
      return /* Node */[
              v,
              insert(l, value),
              r
            ];
    } else {
      return /* Node */[
              v,
              l,
              insert(r, value)
            ];
    }
  } else {
    return /* Node */[
            value,
            /* Empty */0,
            /* Empty */0
          ];
  }
}

exports.print  = print;
exports.find   = find;
exports.insert = insert;
/* No side effect */
