// Generated by BUCKLESCRIPT VERSION 1.9.1, PLEASE EDIT WITH CARE
'use strict';

var List       = require("bs-platform/lib/js/list.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function insert(a, v) {
  var match = List.length(a);
  if (match !== 0) {
    if (match !== 1) {
      var match$1 = +(v < List.hd(a));
      if (match$1 !== 0) {
        return /* :: */[
                v,
                a
              ];
      } else {
        return /* :: */[
                List.hd(a),
                insert(List.tl(a), v)
              ];
      }
    } else {
      var match$2 = +(v > List.hd(a));
      if (match$2 !== 0) {
        return /* :: */[
                List.hd(a),
                /* :: */[
                  v,
                  /* [] */0
                ]
              ];
      } else {
        return /* :: */[
                v,
                /* :: */[
                  List.hd(a),
                  /* [] */0
                ]
              ];
      }
    }
  } else {
    return /* :: */[
            v,
            /* [] */0
          ];
  }
}

function sort(a) {
  return List.fold_left(insert, /* [] */0, a);
}

function testPrint(a) {
  List.iter((function (v) {
          Pervasives.print_int(v);
          return Pervasives.print_string(", ");
        }), a);
  return Pervasives.print_string("\n");
}

exports.insert    = insert;
exports.sort      = sort;
exports.testPrint = testPrint;
/* No side effect */
