// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List       = require("bs-platform/lib/js/list.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function sort(l) {
  if (List.length(l) > 1) {
    var hd = List.hd(l);
    return List.concat(/* :: */[
                sort(List.filter((function (x) {
                              return +(x < hd);
                            }))(List.tl(l))),
                /* :: */[
                  /* :: */[
                    hd,
                    /* [] */0
                  ],
                  /* :: */[
                    sort(List.filter((function (x) {
                                  return +(x >= hd);
                                }))(List.tl(l))),
                    /* [] */0
                  ]
                ]
              ]);
  } else {
    return l;
  }
}

function print(a) {
  List.iter((function (v) {
          Pervasives.print_int(v);
          return Pervasives.print_string(", ");
        }), a);
  return Pervasives.print_string("\n");
}

exports.sort  = sort;
exports.print = print;
/* No side effect */
