// Generated by BUCKLESCRIPT VERSION 1.9.1, PLEASE EDIT WITH CARE
'use strict';

var List       = require("bs-platform/lib/js/list.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function push(stack, value) {
  return /* :: */[
          value,
          stack
        ];
}

var peek = List.hd;

var pop = List.tl;

var stack_001 = /* :: */[
  1,
  /* :: */[
    0,
    /* [] */0
  ]
];

var stack = /* :: */[
  2,
  stack_001
];

Pervasives.print_int(List.hd(List.tl(stack)));

exports.push  = push;
exports.peek  = peek;
exports.pop   = pop;
exports.stack = stack;
/*  Not a pure module */
